# This is a basic workflow to help you get started with Actions

name: testGithubCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "TF_runer"
  TF_runer:
    # setting the custermized container
    container: markliou/python3-tensorflow-gpu:latest
    # The type of runner that the job will run on
    # runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Run the python script for test 
      - name: update the ubuntu 
        run: sudo apt update -y; sudo apt upgrade -y; sudo apt install python3-pip sudo
      - name: install TF
        run: |
          pip3 install tensorflow 
          pip3 install tensorflow-addons 
          pip3 install tensorflow-datasets 
      - name: run the TF scripts
        run: python3 hello.py