# This is a basic workflow to help you get started with Actions

name: testGithubCI_selfhosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "TF_runer"
  TF_runer:
    
    # using the markliou/python3-tensorflow-gpu container as runner image. All runner scripts are already run in the container, and the runner is attached to github action.
    # The type of runner that the job will run on
    runs-on: self-hosted


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install the essential package
      - name: install system package
        run: apt update -y ; apt install python3-pip
        
      - name: install TF package
        run: |
          pip3 install tensorflow-addons 
          pip3 install tensorflow-datasets 
      # Run the python script for test 
      - name: run the TF scripts
        run: python3 hello.py
      # run the python unit test play script
      - name: run the unit test
        run: python3 unitest.py
  
  # building the docker image and push it to dockerhub using self-hosted node
  Docker_image_builder:
    # runs-on: [dind]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dockerhub login
        env:
          DOCKER_ACCOUNT: ${{secrets.DOCKER_ACCOUNT}}
          DOCKER_PASSWD: ${{secrets.DOCKER_PASSWD}}
        run: |
          docker login -u DOCKER_ACCOUNT -p DOCKER_PASSWD
          
      - name: build docker image 
        run: |
          docker build -t markliou/dind .

      - name: push to dockerhub
        run: docker push markliou/dind
  